---
- name: Setup a Node.js Application
  hosts: all
  become: true

  vars:
    nodejs_version: 18
    ansible_distribution_release: jammy
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Install GPG
      tags: nodejs, install, setup
      ansible.builtin.package:
        name: gnupg
        update_cache: true
        state: present

    - name: Install the gpg key for nodejs LTS
      ansible.builtin.apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: true

    - name: Install NodeJS
      tags: nodesjs, install
      ansible.builtin.package:
        name: nodejs
        state: present
