---
- name: Self provisioning
  hosts: localhost
  gather_facts: false
  connection: local

  tasks:
    - name: Get current date
      ansible.builtin.command: date
      register: date
      changed_when: true

    - name: Print the current system date
      ansible.builtin.debug:
        var: date.stdout
