---
- name: Setup a Node.js Application
  hosts: all
  become: true

  vars:
    nodejs_version: 18
    ansible_distribution_release: jammy
    node_apps_location: /usr/local/opt/node

  tasks:
    - name: Install GPG
      ansible.builtin.package:
        name: gnupg
        update_cache: true
        state: present

    - name: Install the gpg key for nodejs LTS
      ansible.builtin.apt_key:
        url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
        state: present

    - name: Install the nodejs LTS repos
      ansible.builtin.apt_repository:
        repo: "deb https://deb.nodesource.com/node_{{ nodejs_version }}.x {{ ansible_distribution_release }} main"
        state: present
        update_cache: true

    - name: Install NodeJS
      ansible.builtin.package:
        name: nodejs
        state: present

    - name: Install PM2
      community.general.npm:
        name: pm2
        global: true

    - name: Ensure Node.js app folder exists
      ansible.builtin.file:
        path: "{{ node_apps_location }}"
        state: directory
        mode: 0644

    - name: Copy Node.js app to server
      ansible.builtin.copy:
        src: app
        dest: "{{ node_apps_location }}"
        mode: 0644

    - name: Install app dependencies defined in package.json
      community.general.npm:
        path: "{{ node_apps_location }}/app"

    - name: Start Node.js app
      ansible.builtin.shell:
        cmd: >
          pm2 startOrReload "{{ node_apps_location }}/app/ecosystem.config.cjs"
      changed_when: false
