# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-22.04"

  config.ssh.insert_key = false
  
  config.vm.hostname = "app"
  config.vm.network :private_network, ip: "192.168.60.10"
end
